cabal-version: 3.0
name: migadu
version: 0.1.0.0
license: GPL-3.0-or-later
license-file: LICENSE
author: Berk Özkütük
maintainer: berk@ozkutuk.me
category: Web
build-type: Simple
extra-doc-files: CHANGELOG.md

common common-extensions
  default-extensions:
    DeriveAnyClass
    DuplicateRecordFields
    NoFieldSelectors
    OverloadedRecordDot

  default-language: GHC2024

common warnings
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wpartial-fields
    -Wredundant-constraints
    -fhide-source-paths
    -fshow-hole-constraints
    -Wunused-packages
    -Wunticked-promoted-constructors

library
  import:
    warnings
    , common-extensions

  exposed-modules:
    Migadu
    Migadu.Fields
    Migadu.Identity
    Migadu.Mailbox

  build-depends:
    aeson,
    base ^>=4.20.2.0,
    bytestring,
    req,
    text,
    time,
    typed-process,

  hs-source-dirs: src

test-suite migadu-test
  import:
    warnings
    , common-extensions

  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  build-depends:
    base ^>=4.20.2.0,
    migadu,
