cabal-version: 3.0
name: migaman
version: 0.1.0
license: GPL-3.0-or-later
license-file: LICENSE
author: Berk Özkütük
maintainer: berk@ozkutuk.me
category: Web
build-type: Simple
extra-doc-files: CHANGELOG.md
extra-source-files:
  README.md
  migaman.toml.sample

common common-extensions
  default-extensions:
    DeriveAnyClass
    DuplicateRecordFields
    NoFieldSelectors
    OverloadedRecordDot

  default-language: GHC2024

common warnings
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wpartial-fields
    -Wredundant-constraints
    -fhide-source-paths
    -fshow-hole-constraints
    -Wunused-packages

library
  import:
    warnings
    , common-extensions

  exposed-modules:
    Cli
    IdentityTable.Model
    IdentityTable.Query
    Migaman
    Migrations

  build-depends:
    base ^>=4.20.2.0,
    beam-core,
    beam-sqlite,
    bytestring,
    directory,
    file-embed,
    filepath,
    migadu,
    migrant-core,
    migrant-sqlite-simple,
    optparse-applicative,
    random,
    sqlite-simple,
    tabular,
    text,
    toml-reader,

  hs-source-dirs: src

executable migaman
  import:
    warnings
    , common-extensions

  main-is: Main.hs
  build-depends:
    base ^>=4.20.2.0,
    migaman,

  hs-source-dirs: app

test-suite migaman-test
  import:
    warnings
    , common-extensions

  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  build-depends:
    base ^>=4.20.2.0,
    migaman,
